apiVersion: apps/v1
kind: Deployment
metadata:
  name: course-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: course-deployment
  template:
    metadata:
      labels:
        app: course-deployment
    spec:
      containers:
        - name: course-deployment
          image: arunvaradharajalu/lms-api-course
          resources:
            limits:
              memory: "256Mi"
              cpu: "100m"
          ports:      
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: dev
            - name: MONGODB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: main-mongodb-db-credentials
                  key: MONGODB_USERNAME
            - name: MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: main-mongodb-db-credentials
                  key: MONGODB_PASSWORD
            - name: JWT_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-credentials
                  key: JWT_PRIVATE_KEY
            - name: S3_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: s3-credentials
                  key: S3_ACCESS_KEY_ID
            - name: S3_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: s3-credentials
                  key: S3_SECRET_ACCESS_KEY
            - name: VIDEO_TRANSCODER_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: transcoder-credentials
                  key: VIDEO_TRANSCODER_ACCESS_KEY
            - name: VIDEO_TRANSCODER_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: transcoder-credentials
                  key: VIDEO_TRANSCODER_SECRET_ACCESS_KEY
            - name: STRIPE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: stripe-api-credentials
                  key: STRIPE_API_KEY
        
---

apiVersion: v1
kind: Service
metadata:
  name: course-service
spec:
  type: ClusterIP  
  selector:
    app: course-deployment
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000