apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: student-forgot-password-event
  labels:
    strimzi.io/cluster: my-cluster
spec:
  partitions: 1
  replicas: 1
  config:
    retention.ms: 300000
    segment.bytes: 10485760